const mongoose=require("mongoose");
const courseSchema=new mongoose.Schema({
  courseName:{
    type:String,
    required:true,
    trim:true
  },
  description:{
    type:String,
    required:true,
    trim:true
  },
  instructor:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"User",
    required:true
  },
  whatyouwilllearn:{
   type:String
  },
  ratingAndReview:[
    {
        type:mongoose.Schema.Types.ObjectId,
        ref:"RatingAndReview"
    }
  ],
  price:{
    type:Number
  },
  thumbnail:{
    type:String,

  },
  tag:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Tag"
  },
  createdOn:{
    type:Number
  },
  language:{
    type:String,
    enum:["Hindi","English"]
  },
  courseContent:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"Section",
    require:true
  }],
  enrolledStudent:[{
    type:mongoose.Schema.Types.ObjectId,
    ref:"User",
    require:true
  }]
})
module.exports=mongoose.model("Courses",courseSchema);